project_folder = "t_project_sno"

[connection]
type = "snowflake"
account = "IZOMIWY-AM07852"
user = "mucio"
password = "PASSWORD"
role = "ACCOUNTADMIN"
warehouse = "SNOWFLAKE_LEARNING_WH"
database = "TEST_TEE"
host = "IZOMIWY-AM07852.snowflakecomputing.com"